language: clojure
lein: lein2
jdk:
- openjdk6
deploy:
  provider: heroku
  api_key:
    secure: KlYTdTA9HmbqeWMcC5kjFpIcO8IPBTMt9Jt3A1LbZCOcF4FPuljYzOPWHswldeB5+sZgcGUjKuiGNYSdVov/vmGoBYJDhyFVkexMdPf3dHQQmjfLv39yIxP9Mzn821ba/lQHMOzO3E8h2V5wr+Tx9Jn4wa7jVbv+vnqUbEXiB2Q=
  app: fanhaf-fav-tweet-agent
  on:
    repo: fanhaf/fav-tweet-agent
